---
- name: My First playbook
  hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: Install a list of packages
    yum:
      name:
        - httpd
        - epel-release
        - yum-utils
        - php
        - mysql
        - mariadb
      state: present

  - name: Add Bob
    user:
      name: 
        - Bob
        - ben
        - lisa
        - katty
      generate_ssh_key: yes
      state: present  

